-- ECC Supabase Database Setup Script
-- Run this in the Supabase SQL Editor after creating the project.
-- Then create an Auth user for each admin and insert that user's UUID into public.site_admins.

BEGIN;

-- 1. Tables

CREATE TABLE IF NOT EXISTS public.site_admins (
    user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL CHECK (char_length(name) BETWEEN 1 AND 80),
    role TEXT NOT NULL CHECK (char_length(role) BETWEEN 1 AND 80),
    bio TEXT CHECK (char_length(coalesce(bio, '')) <= 500),
    skills TEXT CHECK (char_length(coalesce(skills, '')) <= 250),
    year TEXT CHECK (char_length(coalesce(year, '')) <= 40),
    github TEXT DEFAULT '#' CHECK (github IS NULL OR github = '#' OR github ~* '^https?://'),
    linkedin TEXT DEFAULT '#' CHECK (linkedin IS NULL OR linkedin = '#' OR linkedin ~* '^https?://'),
    photo_url TEXT CHECK (photo_url IS NULL OR photo_url = '' OR photo_url ~* '^https?://'),
    initials TEXT CHECK (char_length(coalesce(initials, '')) <= 4),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL CHECK (char_length(title) BETWEEN 1 AND 120),
    "desc" TEXT CHECK (char_length(coalesce("desc", '')) <= 600),
    category TEXT NOT NULL DEFAULT 'other' CHECK (category IN ('web', 'mobile', 'ai', 'cloud', 'security', 'other')),
    status TEXT NOT NULL DEFAULT 'Active' CHECK (status IN ('Active', 'Completed', 'Archived')),
    tech TEXT CHECK (char_length(coalesce(tech, '')) <= 250),
    icon TEXT DEFAULT 'CODE' CHECK (char_length(coalesce(icon, '')) <= 16),
    github_url TEXT DEFAULT '#' CHECK (github_url IS NULL OR github_url = '#' OR github_url ~* '^https?://'),
    demo_url TEXT DEFAULT '#' CHECK (demo_url IS NULL OR demo_url = '#' OR demo_url ~* '^https?://'),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL CHECK (char_length(title) BETWEEN 1 AND 120),
    "desc" TEXT CHECK (char_length(coalesce("desc", '')) <= 600),
    date DATE NOT NULL,
    type TEXT NOT NULL DEFAULT 'Other' CHECK (type IN ('Hackathon', 'Competition', 'Workshop', 'Conference', 'Sprint', 'Talk', 'Other')),
    status TEXT NOT NULL DEFAULT 'upcoming' CHECK (status IN ('upcoming', 'ongoing', 'past')),
    venue TEXT CHECK (char_length(coalesce(venue, '')) <= 120),
    participants INTEGER DEFAULT 0 CHECK (participants BETWEEN 0 AND 100000),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    members_count INTEGER DEFAULT 0 CHECK (members_count BETWEEN 0 AND 100000),
    projects_count INTEGER DEFAULT 0 CHECK (projects_count BETWEEN 0 AND 100000),
    hackathons_count INTEGER DEFAULT 0 CHECK (hackathons_count BETWEEN 0 AND 100000),
    awards_count INTEGER DEFAULT 0 CHECK (awards_count BETWEEN 0 AND 100000),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.contact_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL CHECK (char_length(name) BETWEEN 1 AND 80),
    email TEXT NOT NULL CHECK (char_length(email) <= 150 AND email ~* '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'),
    topic TEXT NOT NULL CHECK (topic IN ('Join ECC', 'Collaboration', 'Sponsorship', 'General Query')),
    message TEXT NOT NULL CHECK (char_length(message) BETWEEN 1 AND 1000),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Grants for the Data API

GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT SELECT ON public.members, public.projects, public.events, public.stats TO anon, authenticated;
GRANT INSERT ON public.contact_messages TO anon, authenticated;
GRANT SELECT ON public.site_admins TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.members, public.projects, public.events, public.stats, public.contact_messages TO authenticated;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;

-- 3. Row Level Security

ALTER TABLE public.site_admins ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stats ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own admin status" ON public.site_admins;
CREATE POLICY "Users can view own admin status"
ON public.site_admins
FOR SELECT
TO authenticated
USING (user_id = auth.uid());

DROP POLICY IF EXISTS "Public can view members" ON public.members;
DROP POLICY IF EXISTS "Site admins can insert members" ON public.members;
DROP POLICY IF EXISTS "Site admins can update members" ON public.members;
DROP POLICY IF EXISTS "Site admins can delete members" ON public.members;

CREATE POLICY "Public can view members"
ON public.members
FOR SELECT
TO anon, authenticated
USING (true);

CREATE POLICY "Site admins can insert members"
ON public.members
FOR INSERT
TO authenticated
WITH CHECK (EXISTS (SELECT 1 FROM public.site_admins WHERE user_id = auth.uid()));

CREATE POLICY "Site admins can update members"
ON public.members
FOR UPDATE
TO authenticated
USING (EXISTS (SELECT 1 FROM public.site_admins WHERE user_id = auth.uid()))
WITH CHECK (EXISTS (SELECT 1 FROM public.site_admins WHERE user_id = auth.uid()));

CREATE POLICY "Site admins can delete members"
ON public.members
FOR DELETE
TO authenticated
USING (EXISTS (SELECT 1 FROM public.site_admins WHERE user_id = auth.uid()));

DROP POLICY IF EXISTS "Public can view projects" ON public.projects;
DROP POLICY IF EXISTS "Site admins can insert projects" ON public.projects;
DROP POLICY IF EXISTS "Site admins can update projects" ON public.projects;
DROP POLICY IF EXISTS "Site admins can delete projects" ON public.projects;

CREATE POLICY "Public can view projects"
ON public.projects
FOR SELECT
TO anon, authenticated
USING (true);

CREATE POLICY "Site admins can insert projects"
ON public.projects
FOR INSERT
TO authenticated
WITH CHECK (EXISTS (SELECT 1 FROM public.site_admins WHERE user_id = auth.uid()));

CREATE POLICY "Site admins can update projects"
ON public.projects
FOR UPDATE
TO authenticated
USING (EXISTS (SELECT 1 FROM public.site_admins WHERE user_id = auth.uid()))
WITH CHECK (EXISTS (SELECT 1 FROM public.site_admins WHERE user_id = auth.uid()));

CREATE POLICY "Site admins can delete projects"
ON public.projects
FOR DELETE
TO authenticated
USING (EXISTS (SELECT 1 FROM public.site_admins WHERE user_id = auth.uid()));

DROP POLICY IF EXISTS "Public can view events" ON public.events;
DROP POLICY IF EXISTS "Site admins can insert events" ON public.events;
DROP POLICY IF EXISTS "Site admins can update events" ON public.events;
DROP POLICY IF EXISTS "Site admins can delete events" ON public.events;

CREATE POLICY "Public can view events"
ON public.events
FOR SELECT
TO anon, authenticated
USING (true);

CREATE POLICY "Site admins can insert events"
ON public.events
FOR INSERT
TO authenticated
WITH CHECK (EXISTS (SELECT 1 FROM public.site_admins WHERE user_id = auth.uid()));

CREATE POLICY "Site admins can update events"
ON public.events
FOR UPDATE
TO authenticated
USING (EXISTS (SELECT 1 FROM public.site_admins WHERE user_id = auth.uid()))
WITH CHECK (EXISTS (SELECT 1 FROM public.site_admins WHERE user_id = auth.uid()));

CREATE POLICY "Site admins can delete events"
ON public.events
FOR DELETE
TO authenticated
USING (EXISTS (SELECT 1 FROM public.site_admins WHERE user_id = auth.uid()));

DROP POLICY IF EXISTS "Public can view stats" ON public.stats;
DROP POLICY IF EXISTS "Site admins can insert stats" ON public.stats;
DROP POLICY IF EXISTS "Site admins can update stats" ON public.stats;
DROP POLICY IF EXISTS "Site admins can delete stats" ON public.stats;

CREATE POLICY "Public can view stats"
ON public.stats
FOR SELECT
TO anon, authenticated
USING (true);

CREATE POLICY "Site admins can insert stats"
ON public.stats
FOR INSERT
TO authenticated
WITH CHECK (EXISTS (SELECT 1 FROM public.site_admins WHERE user_id = auth.uid()));

CREATE POLICY "Site admins can update stats"
ON public.stats
FOR UPDATE
TO authenticated
USING (EXISTS (SELECT 1 FROM public.site_admins WHERE user_id = auth.uid()))
WITH CHECK (EXISTS (SELECT 1 FROM public.site_admins WHERE user_id = auth.uid()));

CREATE POLICY "Site admins can delete stats"
ON public.stats
FOR DELETE
TO authenticated
USING (EXISTS (SELECT 1 FROM public.site_admins WHERE user_id = auth.uid()));

DROP POLICY IF EXISTS "Public can insert contact messages" ON public.contact_messages;
DROP POLICY IF EXISTS "Site admins can view contact messages" ON public.contact_messages;
DROP POLICY IF EXISTS "Site admins can update contact messages" ON public.contact_messages;
DROP POLICY IF EXISTS "Site admins can delete contact messages" ON public.contact_messages;

CREATE POLICY "Public can insert contact messages"
ON public.contact_messages
FOR INSERT
TO anon, authenticated
WITH CHECK (true);

CREATE POLICY "Site admins can view contact messages"
ON public.contact_messages
FOR SELECT
TO authenticated
USING (EXISTS (SELECT 1 FROM public.site_admins WHERE user_id = auth.uid()));

CREATE POLICY "Site admins can update contact messages"
ON public.contact_messages
FOR UPDATE
TO authenticated
USING (EXISTS (SELECT 1 FROM public.site_admins WHERE user_id = auth.uid()))
WITH CHECK (EXISTS (SELECT 1 FROM public.site_admins WHERE user_id = auth.uid()));

CREATE POLICY "Site admins can delete contact messages"
ON public.contact_messages
FOR DELETE
TO authenticated
USING (EXISTS (SELECT 1 FROM public.site_admins WHERE user_id = auth.uid()));

-- 4. Storage
-- Current Supabase Storage supports per-bucket file_size_limit and allowed_mime_types.

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
    'member-photos',
    'member-photos',
    true,
    2097152,
    ARRAY['image/jpeg', 'image/png', 'image/webp']
)
ON CONFLICT (id) DO UPDATE
SET public = EXCLUDED.public,
    file_size_limit = EXCLUDED.file_size_limit,
    allowed_mime_types = EXCLUDED.allowed_mime_types;

DROP POLICY IF EXISTS "Public can view member photos" ON storage.objects;
DROP POLICY IF EXISTS "Site admins can upload member photos" ON storage.objects;
DROP POLICY IF EXISTS "Site admins can update member photos" ON storage.objects;
DROP POLICY IF EXISTS "Site admins can delete member photos" ON storage.objects;

CREATE POLICY "Public can view member photos"
ON storage.objects
FOR SELECT
TO anon, authenticated
USING (bucket_id = 'member-photos');

CREATE POLICY "Site admins can upload member photos"
ON storage.objects
FOR INSERT
TO authenticated
WITH CHECK (
    bucket_id = 'member-photos'
    AND storage.extension(name) IN ('jpg', 'jpeg', 'png', 'webp')
    AND EXISTS (SELECT 1 FROM public.site_admins WHERE user_id = auth.uid())
);

CREATE POLICY "Site admins can update member photos"
ON storage.objects
FOR UPDATE
TO authenticated
USING (
    bucket_id = 'member-photos'
    AND EXISTS (SELECT 1 FROM public.site_admins WHERE user_id = auth.uid())
)
WITH CHECK (
    bucket_id = 'member-photos'
    AND storage.extension(name) IN ('jpg', 'jpeg', 'png', 'webp')
    AND EXISTS (SELECT 1 FROM public.site_admins WHERE user_id = auth.uid())
);

CREATE POLICY "Site admins can delete member photos"
ON storage.objects
FOR DELETE
TO authenticated
USING (
    bucket_id = 'member-photos'
    AND EXISTS (SELECT 1 FROM public.site_admins WHERE user_id = auth.uid())
);

-- 5. Seed data

INSERT INTO public.members (id, name, role, bio, skills, year, github, linkedin, initials) VALUES
(1, 'Arjun Sharma', 'President & Full Stack Dev', 'Building scalable web apps and leading the team to victory in hackathons.', 'React,Node.js,Python,AWS', '4th Year', '#', '#', 'AS'),
(2, 'Priya Patel', 'AI/ML Lead', 'Passionate about machine learning and making models that work in production.', 'Python,TensorFlow,PyTorch,MLOps', '3rd Year', '#', '#', 'PP'),
(3, 'Rahul Verma', 'Cybersecurity Expert', 'CTF champion and security researcher focused on practical application security.', 'Pentesting,Kali Linux,Burp Suite,OWASP', '4th Year', '#', '#', 'RV'),
(4, 'Sneha Gupta', 'Cloud Architect', 'AWS certified architect designing cloud solutions for scalability and resilience.', 'AWS,Docker,Kubernetes,Terraform', '3rd Year', '#', '#', 'SG')
ON CONFLICT (id) DO UPDATE SET
    name = EXCLUDED.name,
    role = EXCLUDED.role,
    bio = EXCLUDED.bio,
    skills = EXCLUDED.skills,
    year = EXCLUDED.year,
    github = EXCLUDED.github,
    linkedin = EXCLUDED.linkedin,
    initials = EXCLUDED.initials;

INSERT INTO public.projects (id, title, "desc", category, status, tech, icon, github_url, demo_url) VALUES
(1, 'HealthSync AI', 'AI-powered healthcare platform connecting patients and doctors with smart diagnostics.', 'ai', 'Completed', 'React,Python,TensorFlow,FastAPI', 'AI', '#', '#'),
(2, 'SecureVault', 'End-to-end encrypted password manager with zero-knowledge architecture.', 'security', 'Active', 'Electron,Node.js,CryptoJS,SQLite', 'SEC', '#', '#'),
(3, 'CloudFlow', 'Serverless workflow automation platform built for modern DevOps teams.', 'cloud', 'Active', 'AWS Lambda,React,GraphQL,DynamoDB', 'CLD', '#', '#'),
(4, 'DevConnect', 'Platform for developers to find teammates, collaborate on projects, and grow together.', 'web', 'Completed', 'Next.js,Socket.io,MongoDB,Tailwind', 'WEB', '#', '#')
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    "desc" = EXCLUDED."desc",
    category = EXCLUDED.category,
    status = EXCLUDED.status,
    tech = EXCLUDED.tech,
    icon = EXCLUDED.icon,
    github_url = EXCLUDED.github_url,
    demo_url = EXCLUDED.demo_url;

INSERT INTO public.events (id, title, "desc", date, type, status, venue, participants) VALUES
(1, 'HackFest 2024', '48-hour internal hackathon where teams built innovative solutions. ECC took 1st place.', '2024-11-15', 'Hackathon', 'past', 'Campus Auditorium', 80),
(2, 'AlgoWars Season 3', 'Competitive programming contest testing DSA skills across all ECC members.', '2025-01-20', 'Competition', 'past', 'CS Lab', 45),
(3, 'Summer Build Sprint', 'Week-long build sprint focused on real-world product development from idea to deployment.', '2026-06-15', 'Sprint', 'upcoming', 'Innovation Hub', 60),
(4, 'ECC DevCon 2026', 'Annual developer conference with talks, workshops, and networking from industry experts.', '2026-08-15', 'Conference', 'upcoming', 'Main Auditorium', 200)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    "desc" = EXCLUDED."desc",
    date = EXCLUDED.date,
    type = EXCLUDED.type,
    status = EXCLUDED.status,
    venue = EXCLUDED.venue,
    participants = EXCLUDED.participants;

INSERT INTO public.stats (id, members_count, projects_count, hackathons_count, awards_count) VALUES
(1, 50, 30, 15, 8)
ON CONFLICT (id) DO UPDATE SET
    members_count = EXCLUDED.members_count,
    projects_count = EXCLUDED.projects_count,
    hackathons_count = EXCLUDED.hackathons_count,
    awards_count = EXCLUDED.awards_count,
    updated_at = timezone('utc'::text, now());

SELECT setval(pg_get_serial_sequence('public.members', 'id'), COALESCE((SELECT MAX(id) FROM public.members), 1));
SELECT setval(pg_get_serial_sequence('public.projects', 'id'), COALESCE((SELECT MAX(id) FROM public.projects), 1));
SELECT setval(pg_get_serial_sequence('public.events', 'id'), COALESCE((SELECT MAX(id) FROM public.events), 1));
SELECT setval(pg_get_serial_sequence('public.stats', 'id'), COALESCE((SELECT MAX(id) FROM public.stats), 1));

-- After creating an admin in Supabase Auth, make that user a site admin:
-- INSERT INTO public.site_admins (user_id) VALUES ('00000000-0000-0000-0000-000000000000') ON CONFLICT DO NOTHING;

COMMIT;
